// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBNI0zdA3hQbNivjZx3TTMVxKFWM4JM7g',
    appId: '1:500409929350:web:4199a10e32020d90aecb07',
    messagingSenderId: '500409929350',
    projectId: 'reel-app-ce37d',
    authDomain: 'reel-app-ce37d.firebaseapp.com',
    storageBucket: 'reel-app-ce37d.appspot.com',
    measurementId: 'G-B807JG7MH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7bWjVkKbIYTOuylLDBoYjr9xwslhY9YY',
    appId: '1:500409929350:android:44623cd227f5bb29aecb07',
    messagingSenderId: '500409929350',
    projectId: 'reel-app-ce37d',
    storageBucket: 'reel-app-ce37d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgebPfuVP1ZAbL1fCm_-iEzRx06hTSTFs',
    appId: '1:500409929350:ios:8efa49cde016c057aecb07',
    messagingSenderId: '500409929350',
    projectId: 'reel-app-ce37d',
    storageBucket: 'reel-app-ce37d.appspot.com',
    iosBundleId: 'com.example.reelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgebPfuVP1ZAbL1fCm_-iEzRx06hTSTFs',
    appId: '1:500409929350:ios:8efa49cde016c057aecb07',
    messagingSenderId: '500409929350',
    projectId: 'reel-app-ce37d',
    storageBucket: 'reel-app-ce37d.appspot.com',
    iosBundleId: 'com.example.reelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBNI0zdA3hQbNivjZx3TTMVxKFWM4JM7g',
    appId: '1:500409929350:web:6c1dddf1db9f8345aecb07',
    messagingSenderId: '500409929350',
    projectId: 'reel-app-ce37d',
    authDomain: 'reel-app-ce37d.firebaseapp.com',
    storageBucket: 'reel-app-ce37d.appspot.com',
    measurementId: 'G-JW41TQTG06',
  );
}
